### ISSUE TITLE
Non-iid

### ISSUE THREAD

**Issue by Dora238** [oyhah/DP-RSA#1]
Hi, when I took the experiment in noniid setting, it shows that the path "/dataset_noniid/MNIST" can't find.
I would like to know where is the package or how can I get it.
Wish you all the best~

**Comment by oyhah** [comment]
Hi, thanks for pointing it out. 

The non-iid MNIST dataset divides the hand-written digits into 10 categories. It can be downloaded in the following link: 
https://drive.google.com/file/d/17D99-OE-LWVL_xd4xkBiLoj0QTJg2U_X/view?usp=sharing

I also update it in the Readme page.

Best wishes
